package parser

import (
	"testing"

	"github.com/antlr4-go/antlr/v4"
	"github.com/stretchr/testify/require"

	parser "github.com/ydb-platform/yql-parsers/go"
)

type syntaxErrors struct {
	*antlr.DefaultErrorListener
	messages []string
}

func (l *syntaxErrors) SyntaxError(_ antlr.Recognizer, _ interface{}, _, _ int, message string, _ antlr.RecognitionException) {
	l.messages = append(l.messages, message)
}

type queryListener struct {
	*parser.BaseYQLListener
	selects  int
	literals []string
}

func (l *queryListener) EnterSelect_core(_ *parser.Select_coreContext) {
	l.selects++
}

func (l *queryListener) EnterLiteral_value(ctx *parser.Literal_valueContext) {
	l.literals = append(l.literals, ctx.GetText())
}

func TestParserYQL(t *testing.T) {
	for _, tc := range []struct {
		name     string
		sql      string
		selects  int
		literals []string
		invalid  bool
	}{
		{name: "select literal", sql: "SELECT 1", selects: 1, literals: []string{"1"}},
		{name: "comments and multiple statements", sql: "-- comment\nSELECT 1; SELECT 2;", selects: 2, literals: []string{"1", "2"}},
		{name: "missing expression", sql: "SELECT FROM orders", invalid: true},
		{name: "invalid trailing statement", sql: "SELECT 1; SELECT", invalid: true},
		{name: "invalid character", sql: "SELECT 1 \x00", invalid: true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			errors := &syntaxErrors{DefaultErrorListener: antlr.NewDefaultErrorListener()}
			lexer := parser.NewYQLLexer(antlr.NewInputStream(tc.sql))
			lexer.RemoveErrorListeners()
			lexer.AddErrorListener(errors)
			stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)
			p := parser.NewYQLParser(stream)
			p.RemoveErrorListeners()
			p.AddErrorListener(errors)
			query := p.Sql_query()
			// Check full input consumption as well as reported syntax errors.
			atEOF := stream.LA(1) == antlr.TokenEOF
			if tc.invalid {
				require.True(t, len(errors.messages) > 0 || !atEOF, "invalid SQL was accepted")
				return
			}
			require.Empty(t, errors.messages)
			require.True(t, atEOF, "parser must consume the complete query")
			listener := &queryListener{BaseYQLListener: &parser.BaseYQLListener{}}
			antlr.NewParseTreeWalker().Walk(listener, query)
			require.Equal(t, tc.selects, listener.selects)
			require.Equal(t, tc.literals, listener.literals)
		})
	}
}

// ---- generated interface checks ----
var _ antlr.RuleNode = (*parser.Sql_queryContext)(nil)
var _ antlr.RuleNode = (*parser.Sql_stmt_listContext)(nil)
var _ antlr.RuleNode = (*parser.Ansi_sql_stmt_listContext)(nil)
var _ antlr.RuleNode = (*parser.Lambda_bodyContext)(nil)
var _ antlr.RuleNode = (*parser.Lambda_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Sql_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Sql_stmt_coreContext)(nil)
var _ antlr.RuleNode = (*parser.ExprContext)(nil)
var _ antlr.RuleNode = (*parser.Or_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.And_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.Xor_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.Distinct_from_opContext)(nil)
var _ antlr.RuleNode = (*parser.Cond_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Match_opContext)(nil)
var _ antlr.RuleNode = (*parser.Eq_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.Shift_rightContext)(nil)
var _ antlr.RuleNode = (*parser.Rot_rightContext)(nil)
var _ antlr.RuleNode = (*parser.Double_questionContext)(nil)
var _ antlr.RuleNode = (*parser.Neq_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.Bit_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.Add_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.Mul_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.Con_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.Unary_opContext)(nil)
var _ antlr.RuleNode = (*parser.Unary_subexpr_suffixContext)(nil)
var _ antlr.RuleNode = (*parser.Unary_casual_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.In_unary_casual_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.Unary_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.In_unary_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.List_literalContext)(nil)
var _ antlr.RuleNode = (*parser.Expr_dict_listContext)(nil)
var _ antlr.RuleNode = (*parser.Dict_literalContext)(nil)
var _ antlr.RuleNode = (*parser.Expr_struct_listContext)(nil)
var _ antlr.RuleNode = (*parser.Struct_literalContext)(nil)
var _ antlr.RuleNode = (*parser.Atom_exprContext)(nil)
var _ antlr.RuleNode = (*parser.In_atom_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Cast_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Bitcast_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Exists_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Case_exprContext)(nil)
var _ antlr.RuleNode = (*parser.LambdaContext)(nil)
var _ antlr.RuleNode = (*parser.In_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Json_api_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Jsonpath_specContext)(nil)
var _ antlr.RuleNode = (*parser.Json_variable_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Json_variableContext)(nil)
var _ antlr.RuleNode = (*parser.Json_variablesContext)(nil)
var _ antlr.RuleNode = (*parser.Json_common_argsContext)(nil)
var _ antlr.RuleNode = (*parser.Json_case_handlerContext)(nil)
var _ antlr.RuleNode = (*parser.Json_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Json_exists_handlerContext)(nil)
var _ antlr.RuleNode = (*parser.Json_existsContext)(nil)
var _ antlr.RuleNode = (*parser.Json_query_wrapperContext)(nil)
var _ antlr.RuleNode = (*parser.Json_query_handlerContext)(nil)
var _ antlr.RuleNode = (*parser.Json_queryContext)(nil)
var _ antlr.RuleNode = (*parser.Select_subexprContext)(nil)
var _ antlr.RuleNode = (*parser.Select_subexpr_coreContext)(nil)
var _ antlr.RuleNode = (*parser.Select_subexpr_intersectContext)(nil)
var _ antlr.RuleNode = (*parser.Select_or_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Tuple_or_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Smart_parenthesisContext)(nil)
var _ antlr.RuleNode = (*parser.Expr_listContext)(nil)
var _ antlr.RuleNode = (*parser.Pure_column_listContext)(nil)
var _ antlr.RuleNode = (*parser.Pure_column_or_namedContext)(nil)
var _ antlr.RuleNode = (*parser.Pure_column_or_named_listContext)(nil)
var _ antlr.RuleNode = (*parser.Column_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Without_column_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Column_listContext)(nil)
var _ antlr.RuleNode = (*parser.Without_column_listContext)(nil)
var _ antlr.RuleNode = (*parser.Named_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Named_expr_listContext)(nil)
var _ antlr.RuleNode = (*parser.Invoke_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Invoke_expr_tailContext)(nil)
var _ antlr.RuleNode = (*parser.Using_call_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Key_exprContext)(nil)
var _ antlr.RuleNode = (*parser.When_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Literal_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Bind_parameterContext)(nil)
var _ antlr.RuleNode = (*parser.Opt_bind_parameterContext)(nil)
var _ antlr.RuleNode = (*parser.Bind_parameter_listContext)(nil)
var _ antlr.RuleNode = (*parser.Named_bind_parameterContext)(nil)
var _ antlr.RuleNode = (*parser.Named_bind_parameter_listContext)(nil)
var _ antlr.RuleNode = (*parser.Signed_numberContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_simpleContext)(nil)
var _ antlr.RuleNode = (*parser.Integer_or_bindContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_tagContext)(nil)
var _ antlr.RuleNode = (*parser.Struct_argContext)(nil)
var _ antlr.RuleNode = (*parser.Struct_arg_positionalContext)(nil)
var _ antlr.RuleNode = (*parser.Variant_argContext)(nil)
var _ antlr.RuleNode = (*parser.Callable_argContext)(nil)
var _ antlr.RuleNode = (*parser.Callable_arg_listContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_decimalContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_optionalContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_tupleContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_structContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_variantContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_listContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_streamContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_flowContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_dictContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_setContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_enumContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_resourceContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_taggedContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_callableContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_linearContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_dynamiclinearContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_compositeContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_nullContext)(nil)
var _ antlr.RuleNode = (*parser.Type_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Type_name_or_bindContext)(nil)
var _ antlr.RuleNode = (*parser.Value_constructor_literalContext)(nil)
var _ antlr.RuleNode = (*parser.Value_constructorContext)(nil)
var _ antlr.RuleNode = (*parser.Declare_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Module_pathContext)(nil)
var _ antlr.RuleNode = (*parser.Import_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Export_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Call_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Inline_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Do_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Pragma_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Pragma_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Sort_specificationContext)(nil)
var _ antlr.RuleNode = (*parser.Sort_specification_listContext)(nil)
var _ antlr.RuleNode = (*parser.Cte_with_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Cte_bindingContext)(nil)
var _ antlr.RuleNode = (*parser.Cte_keyContext)(nil)
var _ antlr.RuleNode = (*parser.Cte_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Select_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Select_stmt_coreContext)(nil)
var _ antlr.RuleNode = (*parser.Select_stmt_intersectContext)(nil)
var _ antlr.RuleNode = (*parser.Select_unparenthesized_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Select_unparenthesized_stmt_coreContext)(nil)
var _ antlr.RuleNode = (*parser.Select_unparenthesized_stmt_intersectContext)(nil)
var _ antlr.RuleNode = (*parser.Select_kind_parenthesisContext)(nil)
var _ antlr.RuleNode = (*parser.Union_opContext)(nil)
var _ antlr.RuleNode = (*parser.Intersect_opContext)(nil)
var _ antlr.RuleNode = (*parser.Select_kind_partialContext)(nil)
var _ antlr.RuleNode = (*parser.Select_kindContext)(nil)
var _ antlr.RuleNode = (*parser.Process_coreContext)(nil)
var _ antlr.RuleNode = (*parser.External_call_paramContext)(nil)
var _ antlr.RuleNode = (*parser.External_call_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Reduce_coreContext)(nil)
var _ antlr.RuleNode = (*parser.Opt_set_quantifierContext)(nil)
var _ antlr.RuleNode = (*parser.Select_coreContext)(nil)
var _ antlr.RuleNode = (*parser.Combine_coreContext)(nil)
var _ antlr.RuleNode = (*parser.Materialize_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_recognition_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_rows_per_matchContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_empty_match_handlingContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_measuresContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_measure_listContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_measure_definitionContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_common_syntaxContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_skip_toContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_skip_to_variable_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_initial_or_seekContext)(nil)
var _ antlr.RuleNode = (*parser.Row_patternContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_termContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_factorContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_quantifierContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_primaryContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_primary_variable_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_permuteContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_subset_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_subset_listContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_subset_itemContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_subset_item_variable_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_subset_rhsContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_subset_rhs_variable_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_definition_listContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_definitionContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_definition_variable_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_definition_search_conditionContext)(nil)
var _ antlr.RuleNode = (*parser.Search_conditionContext)(nil)
var _ antlr.RuleNode = (*parser.Row_pattern_variable_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Order_by_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Ext_order_by_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Group_by_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Grouping_element_listContext)(nil)
var _ antlr.RuleNode = (*parser.Grouping_elementContext)(nil)
var _ antlr.RuleNode = (*parser.Ordinary_grouping_setContext)(nil)
var _ antlr.RuleNode = (*parser.Ordinary_grouping_set_listContext)(nil)
var _ antlr.RuleNode = (*parser.Rollup_listContext)(nil)
var _ antlr.RuleNode = (*parser.Cube_listContext)(nil)
var _ antlr.RuleNode = (*parser.Grouping_sets_specificationContext)(nil)
var _ antlr.RuleNode = (*parser.Hopping_window_specificationContext)(nil)
var _ antlr.RuleNode = (*parser.Result_columnContext)(nil)
var _ antlr.RuleNode = (*parser.Join_sourceContext)(nil)
var _ antlr.RuleNode = (*parser.Named_columnContext)(nil)
var _ antlr.RuleNode = (*parser.Flatten_by_argContext)(nil)
var _ antlr.RuleNode = (*parser.Flatten_sourceContext)(nil)
var _ antlr.RuleNode = (*parser.Named_single_sourceContext)(nil)
var _ antlr.RuleNode = (*parser.Hinted_single_sourceContext)(nil)
var _ antlr.RuleNode = (*parser.Single_sourceContext)(nil)
var _ antlr.RuleNode = (*parser.Sample_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Tablesample_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Sampling_modeContext)(nil)
var _ antlr.RuleNode = (*parser.Repeatable_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Join_opContext)(nil)
var _ antlr.RuleNode = (*parser.Join_constraintContext)(nil)
var _ antlr.RuleNode = (*parser.Returning_columns_listContext)(nil)
var _ antlr.RuleNode = (*parser.Into_table_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Into_values_sourceContext)(nil)
var _ antlr.RuleNode = (*parser.Values_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Values_sourceContext)(nil)
var _ antlr.RuleNode = (*parser.Values_source_row_listContext)(nil)
var _ antlr.RuleNode = (*parser.Values_source_rowContext)(nil)
var _ antlr.RuleNode = (*parser.Create_external_data_source_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_external_data_source_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_external_data_source_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_external_data_source_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_streaming_query_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_streaming_query_featuresContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_streaming_query_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_streaming_query_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_streaming_query_set_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Streaming_query_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Streaming_query_settingContext)(nil)
var _ antlr.RuleNode = (*parser.Streaming_query_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Streaming_query_definitionContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_streaming_query_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_view_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_view_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Upsert_object_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_object_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_object_featuresContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_object_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_object_featuresContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_object_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_object_featuresContext)(nil)
var _ antlr.RuleNode = (*parser.Object_feature_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Object_feature_kvContext)(nil)
var _ antlr.RuleNode = (*parser.Object_feature_flagContext)(nil)
var _ antlr.RuleNode = (*parser.Object_featureContext)(nil)
var _ antlr.RuleNode = (*parser.Object_featuresContext)(nil)
var _ antlr.RuleNode = (*parser.Object_type_refContext)(nil)
var _ antlr.RuleNode = (*parser.Create_table_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_table_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Create_backup_collection_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_backup_collection_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_backup_collection_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_backup_collection_entriesContext)(nil)
var _ antlr.RuleNode = (*parser.Create_backup_collection_entries_manyContext)(nil)
var _ antlr.RuleNode = (*parser.Table_listContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_backup_collection_actionsContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_backup_collection_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_backup_collection_entriesContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_backup_collection_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Backup_collectionContext)(nil)
var _ antlr.RuleNode = (*parser.Backup_collection_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Backup_collection_settings_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Backup_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Restore_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_database_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_database_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Set_database_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Database_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Database_settingContext)(nil)
var _ antlr.RuleNode = (*parser.Database_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Truncate_table_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.With_truncate_table_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Table_inheritsContext)(nil)
var _ antlr.RuleNode = (*parser.Table_partition_byContext)(nil)
var _ antlr.RuleNode = (*parser.With_table_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Table_tablestoreContext)(nil)
var _ antlr.RuleNode = (*parser.Table_settings_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Table_as_sourceContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_external_table_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_external_table_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_store_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_store_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_add_columnContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_drop_columnContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_columnContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_column_drop_not_nullContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_column_set_not_nullContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_column_set_compressionContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_add_column_familyContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_column_familyContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_set_table_setting_uncompatContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_set_table_setting_compatContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_reset_table_settingContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_add_indexContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_drop_indexContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_add_statisticsContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_drop_statisticsContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_rename_toContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_rename_index_toContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_add_changefeedContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_changefeedContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_drop_changefeedContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_indexContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_rebuild_indexContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_compactContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_column_set_encodingContext)(nil)
var _ antlr.RuleNode = (*parser.Column_schemaContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_column_set_defaultContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_column_drop_defaultContext)(nil)
var _ antlr.RuleNode = (*parser.Column_option_listContext)(nil)
var _ antlr.RuleNode = (*parser.Column_option_list_spaceContext)(nil)
var _ antlr.RuleNode = (*parser.Column_option_list_commaContext)(nil)
var _ antlr.RuleNode = (*parser.Column_optionContext)(nil)
var _ antlr.RuleNode = (*parser.CompressionContext)(nil)
var _ antlr.RuleNode = (*parser.Compression_setting_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Compression_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Family_relationContext)(nil)
var _ antlr.RuleNode = (*parser.NullabilityContext)(nil)
var _ antlr.RuleNode = (*parser.Default_valueContext)(nil)
var _ antlr.RuleNode = (*parser.EncodingContext)(nil)
var _ antlr.RuleNode = (*parser.Encoding_configContext)(nil)
var _ antlr.RuleNode = (*parser.Encoding_config_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Encoding_setting_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Encoding_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Generated_alwaysContext)(nil)
var _ antlr.RuleNode = (*parser.Column_order_by_specificationContext)(nil)
var _ antlr.RuleNode = (*parser.Table_constraintContext)(nil)
var _ antlr.RuleNode = (*parser.Table_indexContext)(nil)
var _ antlr.RuleNode = (*parser.Table_index_typeContext)(nil)
var _ antlr.RuleNode = (*parser.Global_indexContext)(nil)
var _ antlr.RuleNode = (*parser.Local_indexContext)(nil)
var _ antlr.RuleNode = (*parser.Index_subtypeContext)(nil)
var _ antlr.RuleNode = (*parser.With_index_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Index_setting_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Index_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Table_statisticsContext)(nil)
var _ antlr.RuleNode = (*parser.With_statistics_typesContext)(nil)
var _ antlr.RuleNode = (*parser.With_compact_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Compact_setting_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Compact_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.ChangefeedContext)(nil)
var _ antlr.RuleNode = (*parser.Changefeed_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Changefeed_settings_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Changefeed_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Changefeed_alter_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_setting_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Table_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Ttl_tier_listContext)(nil)
var _ antlr.RuleNode = (*parser.Ttl_tier_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Family_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Family_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Family_settings_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Family_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Split_boundariesContext)(nil)
var _ antlr.RuleNode = (*parser.Literal_value_listContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_table_alter_index_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_table_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_user_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_user_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_group_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_group_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_role_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Role_nameContext)(nil)
var _ antlr.RuleNode = (*parser.User_optionContext)(nil)
var _ antlr.RuleNode = (*parser.Authentication_optionContext)(nil)
var _ antlr.RuleNode = (*parser.Password_optionContext)(nil)
var _ antlr.RuleNode = (*parser.Password_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Hash_optionContext)(nil)
var _ antlr.RuleNode = (*parser.Login_optionContext)(nil)
var _ antlr.RuleNode = (*parser.Grant_permissions_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Revoke_permissions_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Permission_idContext)(nil)
var _ antlr.RuleNode = (*parser.Permission_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Permission_name_targetContext)(nil)
var _ antlr.RuleNode = (*parser.Create_resource_pool_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_resource_pool_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_resource_pool_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_resource_pool_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_resource_pool_classifier_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_resource_pool_classifier_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_resource_pool_classifier_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_resource_pool_classifier_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_replication_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Replication_targetContext)(nil)
var _ antlr.RuleNode = (*parser.Replication_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Replication_settings_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_replication_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_replication_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_replication_set_settingContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_replication_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Lambda_or_parameterContext)(nil)
var _ antlr.RuleNode = (*parser.Create_transfer_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Transfer_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Transfer_settings_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_transfer_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_transfer_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_transfer_set_settingContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_transfer_set_usingContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_transfer_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Action_or_subquery_argsContext)(nil)
var _ antlr.RuleNode = (*parser.Define_action_or_subquery_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Define_action_or_subquery_bodyContext)(nil)
var _ antlr.RuleNode = (*parser.If_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.For_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Table_refContext)(nil)
var _ antlr.RuleNode = (*parser.Table_keyContext)(nil)
var _ antlr.RuleNode = (*parser.Table_argContext)(nil)
var _ antlr.RuleNode = (*parser.Table_hintsContext)(nil)
var _ antlr.RuleNode = (*parser.Table_hintContext)(nil)
var _ antlr.RuleNode = (*parser.Object_refContext)(nil)
var _ antlr.RuleNode = (*parser.Simple_table_ref_coreContext)(nil)
var _ antlr.RuleNode = (*parser.Simple_table_refContext)(nil)
var _ antlr.RuleNode = (*parser.Into_simple_table_refContext)(nil)
var _ antlr.RuleNode = (*parser.Delete_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Update_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Set_clause_choiceContext)(nil)
var _ antlr.RuleNode = (*parser.Set_clause_listContext)(nil)
var _ antlr.RuleNode = (*parser.Set_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Set_targetContext)(nil)
var _ antlr.RuleNode = (*parser.Multiple_column_assignmentContext)(nil)
var _ antlr.RuleNode = (*parser.Set_target_listContext)(nil)
var _ antlr.RuleNode = (*parser.Create_topic_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_topic_entriesContext)(nil)
var _ antlr.RuleNode = (*parser.Create_topic_entryContext)(nil)
var _ antlr.RuleNode = (*parser.With_topic_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_topic_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_topic_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_topic_add_consumerContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_create_consumer_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_topic_alter_consumerContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_topic_alter_consumer_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_topic_drop_consumerContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_alter_consumer_setContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_alter_consumer_resetContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_topic_set_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_topic_reset_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_topic_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_settings_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_consumer_with_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_consumer_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_consumer_settings_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_consumer_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_refContext)(nil)
var _ antlr.RuleNode = (*parser.Topic_consumer_refContext)(nil)
var _ antlr.RuleNode = (*parser.Null_treatmentContext)(nil)
var _ antlr.RuleNode = (*parser.Filter_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Window_name_or_specificationContext)(nil)
var _ antlr.RuleNode = (*parser.Window_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Window_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Window_definition_listContext)(nil)
var _ antlr.RuleNode = (*parser.Window_definitionContext)(nil)
var _ antlr.RuleNode = (*parser.New_window_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Window_specificationContext)(nil)
var _ antlr.RuleNode = (*parser.Window_specification_detailsContext)(nil)
var _ antlr.RuleNode = (*parser.Existing_window_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Window_partition_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Window_order_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Window_frame_clauseContext)(nil)
var _ antlr.RuleNode = (*parser.Window_frame_unitsContext)(nil)
var _ antlr.RuleNode = (*parser.Window_frame_extentContext)(nil)
var _ antlr.RuleNode = (*parser.Window_frame_betweenContext)(nil)
var _ antlr.RuleNode = (*parser.Window_frame_boundContext)(nil)
var _ antlr.RuleNode = (*parser.Window_frame_exclusionContext)(nil)
var _ antlr.RuleNode = (*parser.Use_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Named_nodes_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Commit_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Rollback_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Analyze_tableContext)(nil)
var _ antlr.RuleNode = (*parser.Analyze_table_listContext)(nil)
var _ antlr.RuleNode = (*parser.Analyze_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_sequence_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_sequence_actionContext)(nil)
var _ antlr.RuleNode = (*parser.Show_create_table_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Create_secret_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.With_secret_settingsContext)(nil)
var _ antlr.RuleNode = (*parser.Secret_setting_entryContext)(nil)
var _ antlr.RuleNode = (*parser.Secret_setting_valueContext)(nil)
var _ antlr.RuleNode = (*parser.Alter_secret_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.Drop_secret_stmtContext)(nil)
var _ antlr.RuleNode = (*parser.IdentifierContext)(nil)
var _ antlr.RuleNode = (*parser.IdContext)(nil)
var _ antlr.RuleNode = (*parser.Id_schemaContext)(nil)
var _ antlr.RuleNode = (*parser.Id_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Id_expr_inContext)(nil)
var _ antlr.RuleNode = (*parser.Id_windowContext)(nil)
var _ antlr.RuleNode = (*parser.Id_tableContext)(nil)
var _ antlr.RuleNode = (*parser.Id_withoutContext)(nil)
var _ antlr.RuleNode = (*parser.Id_hintContext)(nil)
var _ antlr.RuleNode = (*parser.Id_as_compatContext)(nil)
var _ antlr.RuleNode = (*parser.An_idContext)(nil)
var _ antlr.RuleNode = (*parser.An_id_or_typeContext)(nil)
var _ antlr.RuleNode = (*parser.An_id_schemaContext)(nil)
var _ antlr.RuleNode = (*parser.An_id_exprContext)(nil)
var _ antlr.RuleNode = (*parser.An_id_expr_inContext)(nil)
var _ antlr.RuleNode = (*parser.An_id_windowContext)(nil)
var _ antlr.RuleNode = (*parser.An_id_tableContext)(nil)
var _ antlr.RuleNode = (*parser.An_id_withoutContext)(nil)
var _ antlr.RuleNode = (*parser.An_id_hintContext)(nil)
var _ antlr.RuleNode = (*parser.An_id_pureContext)(nil)
var _ antlr.RuleNode = (*parser.An_id_as_compatContext)(nil)
var _ antlr.RuleNode = (*parser.View_nameContext)(nil)
var _ antlr.RuleNode = (*parser.Opt_id_prefixContext)(nil)
var _ antlr.RuleNode = (*parser.Cluster_exprContext)(nil)
var _ antlr.RuleNode = (*parser.Id_or_typeContext)(nil)
var _ antlr.RuleNode = (*parser.Opt_id_prefix_or_typeContext)(nil)
var _ antlr.RuleNode = (*parser.Id_or_atContext)(nil)
var _ antlr.RuleNode = (*parser.Id_table_or_typeContext)(nil)
var _ antlr.RuleNode = (*parser.Id_table_or_atContext)(nil)
var _ antlr.RuleNode = (*parser.KeywordContext)(nil)
var _ antlr.RuleNode = (*parser.Keyword_expr_uncompatContext)(nil)
var _ antlr.RuleNode = (*parser.Keyword_table_uncompatContext)(nil)
var _ antlr.RuleNode = (*parser.Keyword_select_uncompatContext)(nil)
var _ antlr.RuleNode = (*parser.Keyword_alter_uncompatContext)(nil)
var _ antlr.RuleNode = (*parser.Keyword_in_uncompatContext)(nil)
var _ antlr.RuleNode = (*parser.Keyword_window_uncompatContext)(nil)
var _ antlr.RuleNode = (*parser.Keyword_hint_uncompatContext)(nil)
var _ antlr.RuleNode = (*parser.Keyword_as_compatContext)(nil)
var _ antlr.RuleNode = (*parser.Keyword_compatContext)(nil)
var _ antlr.RuleNode = (*parser.Type_idContext)(nil)
var _ antlr.RuleNode = (*parser.Bool_valueContext)(nil)
var _ antlr.RuleNode = (*parser.RealContext)(nil)
var _ antlr.RuleNode = (*parser.IntegerContext)(nil)
